import Providers from "@/components/Providers";
import QueryProviders from "@/components/QueryProviders";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bitsol - Registration",
  description: "Generated by Bitsol technologies",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-right" />
        <SessionWrapper>
          <QueryProviders>
            <Providers>{children}</Providers>
          </QueryProviders>
        </SessionWrapper>
      </body>
    </html>
  );
}
