import DynamicBodyContent from "@/components/DynamicBodyContent";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bitsol - Registration",
  description: "Generated by Bitsol technologies",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicBodyContent>{children}</DynamicBodyContent>
      </body>
    </html>
  );
}
